Fix Error When Running NPM Test
Fixes error when running npm test

"npm test

> @humanwhocodes/computer-science-in-javascript@2.0.0 test /computer-science-in-javascript
> npm run lint && mocha tests/**/*.js

> @humanwhocodes/computer-science-in-javascript@2.0.0 lint /computer-science-in-javascript
> eslint src/ tests/

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module '@humanwhocodes/doubly-linked-list'
Require stack:
- /computer-science-in-javascript/src/data-structures/hash-map/hash-map.js
- /computer-science-in-javascript/tests/data-structures/hash-map/hash-map.js
- /computer-science-in-javascript/node_modules/mocha/lib/mocha.js
- /computer-science-in-javascript/node_modules/mocha/index.js
- /computer-science-in-javascript/node_modules/mocha/bin/_mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/computer-science-in-javascript/src/data-structures/hash-map/hash-map.js:12:30)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/computer-science-in-javascript/tests/data-structures/hash-map/hash-map.js:12:21)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at /computer-science-in-javascript/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/computer-science-in-javascript/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/computer-science-in-javascript/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/computer-science-in-javascript/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/computer-science-in-javascript/src/data-structures/hash-map/hash-map.js',
    '/computer-science-in-javascript/tests/data-structures/hash-map/hash-map.js',
    '/computer-science-in-javascript/node_modules/mocha/lib/mocha.js',
    '/computer-science-in-javascript/node_modules/mocha/index.js',
    '/computer-science-in-javascript/node_modules/mocha/bin/_mocha'
  ]
}
npm ERR! Test failed.  See above for more details."